<div class="row">
    <div class="col-m-6">
        <div class="dashboard-item" data-bind="scope: 'componentOne'">
            <div class="dashboard-item-title" data-bind="text: title"></div>
            <div class="dashboard-item-content">
                <p>Change value component: <input  data-bind="value: value" ></p>
            </div>
        </div>
    </div>
    <div class="col-m-6">
        <div class="dashboard-item" data-bind="scope: 'componentTwo'">
            <div class="dashboard-item-title" data-bind="text: title"></div>
            <div class="dashboard-item-content">
                <p>Export from the first component: <input  data-bind="value: value" ></p>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "componentOne": {
                        "component": "BelVG_Theme/js/component-one"
                    },
                    "componentTwo": {
                        "component": "BelVG_Theme/js/component-two"
                    }
                }
            }
        }
    }
</script>
